// loot drops
// folklore essence
const luminousEssence = {
	radius: 20,
	name: "luminousEssence",
	spellBookName: null,
	rarity: "common",
	dropChance: 100,
	appearance: "glowstone.webp",
	form: "essence",
	type: "luminous",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "luminousEssence"
};
const gloomEssence = {
	radius: 20,
	name: "gloomEssence",
	spellBookName: null,
	rarity: "common",
	dropChance: 100,
	appearance: "glowstone.webp",
	form: "essence",
	type: "gloom",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "gloomEssence"
};
// folklore Pages
const spikePage = {
	radius: 20,
	name: "spikePage",
	spellBookName: spikeBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "spike"
};
const luminousEnergyPage = {
	radius: 20,
	name: "luminousEnergyPage",
	spellBookName: luminousEnergyBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "luminous",
	essenceName: "luminousEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "lumenergy"
};
const luminousShieldPage = {
	radius: 20,
	name: "luminousShieldPage",
	spellBookName: luminousShieldBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "luminous",
	essenceName: "luminousEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "lumshield"
};
const luminousSpiritPage = {
	radius: 20,
	name: "luminousSpiritPage",
	spellBookName: luminousSpiritBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "luminous",
	essenceName: "luminousEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "spirit"
};
const specterPage = {
	radius: 20,
	name: "specterPage",
	spellBookName: specterBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "specter"
};
const teleportPage = {
	radius: 20,
	name: "teleportPage",
	spellBookName: teleportBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "luminous",
	essenceName: "luminousEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "teleport"
};
const smashPage = {
	radius: 20,
	name: "smashPage",
	spellBookName: smashBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "enchantedBook.png",
	form: "page",
	type: "fire",
	essenceName: "fireEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "smash"
};