// main spells 
const mainSpike = {
	radius: 12,
	name: "spikeBook",
	art: "books",
	shape: "circle",
	appearance: "spike.png",
//	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousEnergy = {
	radius: 12,
	name: "luminousEnergyBook",
	art: "books",
	shape: "circle",
	appearance: "luminousRock.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousSpirit = {
	radius: 12,
	name: "luminousSpiritBook",
	art: "books",
	shape: "circle",
	appearance: "luminousSpirit.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSpecter = {
	radius: 12,
	name: "specterBook",
	art: "books",
	shape: "circle",
	appearance: "specter.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainTeleport = {
	radius: 12,
	name: "teleportBook",
	art: "books",
	shape: "circle",
	appearance: "teleportation.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSmash = {
	radius: 12,
	name: "smashBook",
	art: "books",
	shape: "circle",
	appearance: "smash.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainBeam = {
	radius: 12,
	name: "beamBook",
	art: "books",
	shape: "circle",
	appearance: "beam.webp",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLightningBolt = {
	radius: 12,
	name: "lightningBoltBook",
	art: "books",
	shape: "circle",
	appearance: "lightningBolt.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainEnergyBall = {
	radius: 12,
	name: "energyBallBook",
	art: "books",
	shape: "circle",
	appearance: "energyBall.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousShield = {
	radius: 12,
	name: "luminousShieldBook",
	art: "books",
	shape: "circle",
	appearance: "luminousRock.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}