// main spells 
const mainSpike = {
	radius: 12,
	name: "mainSpike",
	art: "books",
	shape: "circle",
	appearance: "spike.svg",
//	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousEnergy = {
	radius: 12,
	name: "mainLuminousEnergy",
	art: "books",
	shape: "circle",
	appearance: "luminousRock.svg",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousSpirit = {
	radius: 12,
	name: "mainLuminousSpirit",
	art: "books",
	shape: "circle",
	appearance: "luminousSpirit.svg",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSpecter = {
	radius: 12,
	name: "mainSpecter",
	art: "books",
	shape: "circle",
	appearance: "specter.svg",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSpecterHand = {
	radius: 12,
	name: "mainSpecterHand",
	art: "books",
	shape: "circle",
	appearance: "specterHand.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainTeleport = {
	radius: 12,
	name: "mainTeleport",
	art: "books",
	shape: "circle",
	appearance: "teleportation.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSmash = {
	radius: 12,
	name: "mainSmash",
	art: "books",
	shape: "circle",
	appearance: "smash.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainBeam = {
	radius: 12,
	name: "mainBeam",
	art: "books",
	shape: "circle",
	appearance: "beam.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLightningBolt = {
	radius: 12,
	name: "mainLightningBolt",
	art: "books",
	shape: "circle",
	appearance: "lightningBolt.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainEnergyBall = {
	radius: 12,
	name: "mainEnergyBall",
	art: "books",
	shape: "circle",
	appearance: "energyBall.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousShield = {
	radius: 12,
	name: "mainLuminousShield",
	art: "books",
	shape: "circle",
	appearance: "luminousRock.svg",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainTree = {
	radius: 12,
	name: "mainTree",
	art: "books",
	shape: "circle",
	appearance: "gloomForestTree.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}