// mobs
const luminousRock = {
    setMinX: 10,
    setMaxX: 2000,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 0,
    FOVRadius: 0,
    maxAmount: 15,
    name: "luminousRock",
    side: "darkForest",
    appearance: "luminousRock.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 0,
    damage: 1.5,
    type: "passive",
    ability: "nothing",
    learnedSpells: null,
    experienceDrop: 10,
    lootDrop: [luminousEssence, luminousEnergyPage, luminousShieldPage],
    intelligence: 0,
    respawnTime: 3000
};
const luminousSpirit = {
    setMinX: 1000,
    setMaxX: 2500,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 0,
    FOVRadius: 0,
    maxAmount: 15,
    name: "luminousSpirit",
    side: "darkForest",
    appearance: "luminousSpirit.png",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 70,
    defense: 0,
    damage: 2,
    type: "passive",
    ability: "nothing",
    learnedSpells: null,
    experienceDrop: 15,
    lootDrop: [luminousEssence, luminousSpiritPage],
    intelligence: 1,
    respawnTime: 4000
};
const specter = {
    setMinX: 1500,
    setMaxX: 2500,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 0,
    FOVRadius: 250,
    maxAmount: 5,
    name: "specter",
    side: "darkForest",
    appearance: "specter.png",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 80,
    defense: 0,
    damage: 3,
    type: "hostile",
    ability: "chases",
    learnedSpells: null,
    experienceDrop: 20,
    lootDrop: [gloomEssence, specterPage],
    intelligence: 1,
    respawnTime: 8000
};
const darkForestTree = {
    setMinX: 10,
    setMaxX: 2000,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 20,
    FOVRadius: 0,
    maxAmount: 20,
    name: "darkForestTree",
    side: "darkForest",
    appearance: "darkForestTree.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 1.5,
    type: "passive",
    ability: "nothing",
    learnedSpells: null,
    experienceDrop: 15,
    lootDrop: [gloomEssence, spikePage],
    intelligence: 0,
    respawnTime: 8000
};
const darkForestTreant = {
    setMinX: 10,
    setMaxX: 2000,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 20,
    FOVRadius: 250,
    maxAmount: 5,
    name: "darkForestTreant",
    side: "darkForest",
    appearance: "darkForestTreant.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 3,
    type: "hostile",
    ability: "aimedShooting",
    learnedSpells: castSpike,
    experienceDrop: 20,
    lootDrop: [gloomEssence, spikePage],
    intelligence: 0,
    respawnTime: 8000
};