// mobs
const luminousRock = {
    setMinX: 10,
    setMaxX: 2000,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 0,
    maxAmount: 15,
    mobName: "luminousRock",
    appearance: "luminousRock.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 0,
    damage: 1,
    type: "passive",
    ability: "nothing",
    experienceDrop: 10,
    lootDrop: luminousEnergyLootDrop,
    intelligence: 0,
    respawnTime: 3000
};
const luminousSpirit = {
    setMinX: 1000,
    setMaxX: 2500,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 0,
    maxAmount: 5,
    mobName: "luminousSpirit",
    appearance: "luminousSpirit.png",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 70,
    defense: 0,
    damage: 1,
    type: "passive",
    ability: "nothing",
    experienceDrop: 15,
    lootDrop: luminousSpiritLootDrop,
    intelligence: 1,
    respawnTime: 4000
};
const specter = {
    setMinX: 1500,
    setMaxX: 2500,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 0,
    maxAmount: 5,
    mobName: "specter",
    appearance: "specter.png",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 80,
    defense: 0,
    damage: 3,
    type: "hostile",
    ability: "nothing",
    experienceDrop: 20,
    lootDrop: specterLootDrop,
    intelligence: 1,
    respawnTime: 8000
};
const darkForestTree = {
    setMinX: 10,
    setMaxX: 2000,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 20,
    maxAmount: 20,
    mobName: "darkForestTree",
    appearance: "darkForestTree.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 1,
    type: "passive",
    ability: "nothing",
    experienceDrop: 15,
    lootDrop: spikeLootDrop,
    intelligence: 0,
    respawnTime: 8000
};
const darkForestTreant = {
    setMinX: 10,
    setMaxX: 2000,
    setMinY: 10,
    setMaxY: 1000,
    radiusAdjust: 20,
    maxAmount: 5,
    mobName: "darkForestTreant",
    appearance: "darkForestTreant.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 3,
    type: "neutral", // keep in mind that they should be hostile
    ability: "nothing", // treant should have an ability
    experienceDrop: 20,
    lootDrop: spikeLootDrop,
    intelligence: 0,
    respawnTime: 8000
};