// spell books
const spikeBook = {
	radius: 12,
	name: "spikeBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const luminousEnergyBook = {
	radius: 12,
	name: "luminousEnergyBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const luminousSpiritBook = {
	radius: 12,
	name: "luminousSpiritBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const specterBook = {
	radius: 12,
	name: "specterBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const teleportBook = {
	radius: 12,
	name: "teleportBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const smashBook = {
	radius: 12,
	name: "smashBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const beamBook = {
	radius: 12,
	name: "beamBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const lightningBoltBook = {
	radius: 12,
	name: "lightningBoltBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const energyBallBook = {
	radius: 12,
	name: "energyBallBook",
	art: "books",
	shape: "circle",
	appearance: "enchantedBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}