// spells
const castSpike = {
	radius: 12,
	name: "castSpike",
	art: "projecting",
	shape: "circle",
	appearance: "spike.png",
	castAmount: 1,
	maxAmount: 0,
	ignoreSpellCollision: false,
	ignoreMobCollision: false,
	index: 1,
	health: 5,
	defense: 0,
	damage: 3,
	speed: 10,
	ability: "shoot1",
	manaCost: 0.1,
	respawnTime: 500
};
const castLuminousEnergy = {
	radius: 5,
	name: "castLuminousEnergy",
	art: "projecting",
	shape: "circle",
	appearance: "luminousRock.png",
	castAmount: 5,
	maxAmount: 5,
	ignoreSpellCollision: false,
	ignoreMobCollision: false,
	index: 1,
	health: 5,
	defense: 0,
	damage: 1,
	speed: 15,
	ability: "shoot2",
	manaCost: 1.25,
	respawnTime: 1000
}
const summonSpirit = {
	radius: 15,
	name: "summonSpirit",
	art: "summoning",
	shape: "circle",
	appearance: "luminousSpirit.png",
	castAmount: 8,
	maxAmount: 8,
	ignoreSpellCollision: false,
	ignoreMobCollision: false,
	index: 1,
	health: 10,
	defense: 0,
	damage: 3,
	speed: 5,
	ability: "summon1",
	manaCost: 1.75,
	respawnTime: 1000
};
const summonSpecter = {
	radius: 15,
	name: "summonSpecter",
	art: "summoning",
	shape: "circle",
	appearance: "specter.png",
	castAmount: 5,
	maxAmount: 5,
	ignoreSpellCollision: false,
	ignoreMobCollision: false,
	index: 1,
	health: 25, 
	defense: 0,
	damage: 5,
	speed: 7,
	ability: "summon1",
	manaCost: 2.5,
	respawnTime: 1500
};
const teleport = {
	radius: 12,
	name: "teleport",
	art: "evading",
	shape: "circle",
	appearance: "teleportation.png",
	castAmount: 1,
	maxAmount: 0,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 15,
	defense: 0,
	damage: 0,
	speed: 30,
	ability: "teleport",
	manaCost: 2,
	respawnTime: 500
};
const smash = {
	radius: 30,
	name: "smash",
	art: "AoE",
	shape: "circle",
	appearance: "smash.png",
	castAmount: 15,
	maxAmount: 0,
	ignoreSpellCollision: true,
	ignoreMobCollision: false,
	index: 1,
	health: 1,
	defense: 0,
	damage: 2.5,
	speed: 0,
	ability: "AoE1",
	manaCost: 3,
	respawnTime: 500
};
const castBeam = {
	radius: 0,
	name: "castBeam",
	art: "beams",
	shape: "line",
	appearance: "beam.webp",
	castAmount: 1,
	maxAmount: 0,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 10000,
	defense: 0,
	damage: 0.5,
	speed: 10,
	ability: "beam1",
	manaCost: 1,
	respawnTime: 500
};
const castLightningBolt = {
	radius: 0,
	name: "castLightningBolt",
	art: "beams",
	shape: "line",
	appearance: "lightningBolt.png",
	castAmount: 5,
	maxAmount: 0,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 0,
	damage: 3,
	speed: 10,
	ability: "beam2",
	manaCost: 2,
	respawnTime: 500
};
const castEnergyBall = {
	radius: 450,
	name: "castEnergyBall",
	art: "projectile",
	shape: "circle",
	appearance: "energyBall.png",
	castAmount: 1,
	maxAmount: 0,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 2500,
	defense: 0,
	damage: 3,
	speed: 10,
	ability: "shoot1",
	manaCost: 1,
	respawnTime: 500
};