// loot drops
// potions
const manaOrb = {
	radius: 20,
	name: "manaOrb",
	spellBookName: null,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/manaOrb.png",
	form: "effect",
	type: "others",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "spike"
};
// folklore essence
const glowEssence = {
	radius: 20,
	name: "glowEssence",
	spellBookName: null,
	rarity: "common",
	dropChance: 100,
	appearance: "lootDrop/glowEssence.png",
	form: "essence",
	type: "glow",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "Glow Essence"
};
const gloomEssence = {
	radius: 20,
	name: "gloomEssence",
	spellBookName: null,
	rarity: "common",
	dropChance: 100,
	appearance: "lootDrop/gloomEssence.png",
	form: "essence",
	type: "gloom",
	essenceName: null,
	pagesToCraft: null,
	essenceToCraft: null,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "Gloom Essence"
};
// folklore Pages
const spikePage = {
	radius: 20,
	name: "spikePage",
	spellBookName: spikeBook,
	rarity: "uncommon",
	dropChance: 250,
	appearance: "lootDrop/spike_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "spike"
};
const luminousEnergyPage = {
	radius: 20,
	name: "luminousEnergyPage",
	spellBookName: luminousEnergyBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/luminousEnergy_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "lumenergy"
};
const luminousShieldPage = {
	radius: 20,
	name: "luminousShieldPage",
	spellBookName: luminousShieldBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/luminousShield_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "lumshield"
};
const luminousSpiritPage = {
	radius: 20,
	name: "luminousSpiritPage",
	spellBookName: luminousSpiritBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/luminousSpirit_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "spirit"
};
const specterPage = {
	radius: 20,
	name: "specterPage",
	spellBookName: specterBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/specter_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "specter"
};
const teleportPage = {
	radius: 20,
	name: "teleportPage",
	spellBookName: teleportBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/teleport_page.png",
	form: "page",
	type: "glow",
	essenceName: "glowEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "teleport"
};
const smashPage = {
	radius: 20,
	name: "smashPage",
	spellBookName: smashBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/smash_page.png",
	form: "page",
	type: "fire",
	essenceName: "fireEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "smash"
};
const specterHandPage = {
	radius: 20,
	name: "specterHandPage",
	spellBookName: specterHandBook,
	rarity: "uncommon",
	dropChance: 25,
	appearance: "lootDrop/specterHand_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "hand"
};
const treePage = {
	radius: 20,
	name: "treePage",
	spellBookName: treeBook,
	rarity: "rare",
	dropChance: 10,
	appearance: "lootDrop/summonTree_page.png",
	form: "page",
	type: "gloom",
	essenceName: "gloomEssence",
	pagesToCraft: 5,
	essenceToCraft: 15,
	ignoreCollision: false,
	amount: 1,
	stackLimit: 64,
	text: "tree"
};