// main spells 
const mainSpike = {
	radius: 12,
	name: "mainSpike",
	art: "books",
	shape: "circle",
	appearance: "spellBook/spike_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousEnergy = {
	radius: 12,
	name: "mainLuminousEnergy",
	art: "books",
	shape: "circle",
	appearance: "spellBook/luminousEnergy_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainGlowShard = {
	radius: 12,
	name: "mainGlowShard",
	art: "books",
	shape: "circle",
	appearance: "spellBook/glowShard_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousSpirit = {
	radius: 12,
	name: "mainLuminousSpirit",
	art: "books",
	shape: "circle",
	appearance: "spellBook/luminousSpirit_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSpecter = {
	radius: 12,
	name: "mainSpecter",
	art: "books",
	shape: "circle",
	appearance: "spellBook/specter_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSpecterHand = {
	radius: 12,
	name: "mainSpecterHand",
	art: "books",
	shape: "circle",
	appearance: "spellBook/specterHand_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainTeleport = {
	radius: 12,
	name: "mainTeleport",
	art: "books",
	shape: "circle",
	appearance: "spellBook/teleportation_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainSmash = {
	radius: 12,
	name: "mainSmash",
	art: "books",
	shape: "circle",
	appearance: "spellBook/smash_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainBeam = {
	radius: 12,
	name: "mainBeam",
	art: "books",
	shape: "circle",
	appearance: "spellBook/beam_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLightningBolt = {
	radius: 12,
	name: "mainLightningBolt",
	art: "books",
	shape: "circle",
	appearance: "spellBook/lightningBolt_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainEnergyBall = {
	radius: 12,
	name: "mainEnergyBall",
	art: "books",
	shape: "circle",
	appearance: "spellBook/energyBall_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainLuminousShield = {
	radius: 12,
	name: "mainLuminousShield",
	art: "books",
	shape: "circle",
	appearance: "spellBook/luminousShield_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}
const mainTree = {
	radius: 12,
	name: "mainTree",
	art: "books",
	shape: "circle",
	appearance: "spellBook/summonTree_spellBook.png",
	castAmount: 1,
	maxAmount: 1,
	ignoreSpellCollision: true,
	ignoreMobCollision: true,
	index: 1,
	health: 100,
	defense: 100,
	damage: 0,
	speed: 12,
	ability: null,
	manaCost: 1,
	respawnTime: null
}