// mobs
const luminousRock = {
    setMinX: 5000,
    setMaxX: 10000,
    setMinY: 0,
    setMaxY: 10000,
    radiusAdjust: 0,
    movementSpeed: null,
    turnSpeed: null,
    FOVRadius: 0,
    maxAmount: 25,
    name: "luminousRock",
    side: "glowGarden",
    appearance: "mob/luminousRock.svg",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 0,
    damage: 1.5,
    type: "passive",
    ability: "shrinksOnDamage",
    learnedSpells: null,
    castAmount: null,
    castDelay: null,
    experienceDrop: 10,
    lootDrop: [glowEssence, luminousEnergyPage, luminousShieldPage, manaOrb],
    intelligence: 0,
    respawnTime: 3000
};
const luminousSpirit = {
    setMinX: 5000,
    setMaxX: 10000,
    setMinY: 0,
    setMaxY: 10000,
    radiusAdjust: 0,
    movementSpeed: 3,
    turnSpeed: null,
    FOVRadius: 0,
    maxAmount: 15,
    name: "luminousSpirit",
    side: "glowGarden",
    appearance: "mob/luminousSpirit.svg",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 70,
    defense: 0,
    damage: 3,
    type: "passive",
    ability: "nothing",
    learnedSpells: null,
    castAmount: null,
    castDelay: null,
    experienceDrop: 15,
    lootDrop: [glowEssence, luminousSpiritPage, manaOrb],
    intelligence: 1,
    respawnTime: 4000
};
const zapper = {
    setMinX: 8000,
    setMaxX: 10000,
    setMinY: 0,
    setMaxY: 10000,
    radiusAdjust: 0,
    movementSpeed: 3,
    turnSpeed: 0.05,
    FOVRadius: 250,
    maxAmount: 5,
    name: "zapper",
    side: "glowGarden",
    appearance: "mob/zapper.png",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 70,
    defense: 1,
    damage: 3,
    type: "hostile",
    ability: "aimedCasting",
    learnedSpells: castLightningBolt,
    castAmount: 3,
    castDelay: 120,
    experienceDrop: 15,
    lootDrop: [glowEssence, manaOrb],
    intelligence: 1,
    respawnTime: 4000
};
const specter = {
    setMinX: 0,
    setMaxX: 4000,
    setMinY: 2500,
    setMaxY: 7500,
    radiusAdjust: 0,
    movementSpeed: 3,
    turnSpeed: null,
    FOVRadius: 250,
    maxAmount: 10,
    name: "specter",
    side: "gloomForest",
    appearance: "mob/specter.svg",
    ignoreSpellCollision: false,
    ignoreMobCollision: false,
    setMinHealth: 25,
    setMaxHealth: 80,
    defense: 0,
    damage: 5,
    type: "hostile",
    ability: "chases",
    learnedSpells: null,
    castAmount: null,
    castDelay: null,
    experienceDrop: 20,
    lootDrop: [gloomEssence, specterHandPage, manaOrb],
    intelligence: 1,
    respawnTime: 8000
};
const gloomForestTree = {
    setMinX: 0,
    setMaxX: 5000,
    setMinY: 0,
    setMaxY: 10000,
    radiusAdjust: 20,
    movementSpeed: null,
    turnSpeed: null,
    FOVRadius: 0,
    maxAmount: 30,
    name: "gloomForestTree",
    side: "gloomForest",
    appearance: "mob/gloomForestTree.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 1.5,
    type: "passive",
    ability: "nothing",
    learnedSpells: null,
    castAmount: null,
    castDelay: null,
    experienceDrop: 15,
    lootDrop: [gloomEssence, treePage, manaOrb],
    intelligence: 0,
    respawnTime: 8000
};
const gloomForestTreant = {
    setMinX: 0,
    setMaxX: 5000,
    setMinY: 0,
    setMaxY: 10000,
    radiusAdjust: 20,
    movementSpeed: null,
    turnSpeed: 0.01,
    FOVRadius: 250,
    maxAmount: 10,
    name: "gloomForestTreant",
    side: "gloomForest",
    appearance: "mob/gloomForestTreant.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 3,
    type: "hostile",
    ability: "aimedCasting",
    learnedSpells: spikeBook.spell,
    castAmount: 1,
    castDelay: 60,
    experienceDrop: 20,
    lootDrop: [gloomEssence, spikePage, manaOrb],
    intelligence: 0,
    respawnTime: 8000
};

const gloomForestSpecterTreant = {
    setMinX: 0,
    setMaxX: 2000,
    setMinY: 2000,
    setMaxY: 8000,
    radiusAdjust: 20,
    movementSpeed: null,
    turnSpeed: 0.01,
    FOVRadius: 500,
    maxAmount: 5,
    name: "gloomForestSpecterTreant",
    side: "gloomForest",
    appearance: "mob/gloomForestSpecterTreant.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 3,
    type: "summoner",
    ability: "aimedCasting",
    learnedSpells: summonSpecter,
    castAmount: 3,
    castDelay: 180,
    experienceDrop: 20,
    lootDrop: [gloomEssence, specterPage, manaOrb],
    intelligence: 0,
    respawnTime: 32000
};
const luminousSpiritTreant = {
    setMinX: 8000,
    setMaxX: 10000,
    setMinY: 2500,
    setMaxY: 7500,
    radiusAdjust: 20,
    movementSpeed: null,
    turnSpeed: 0.01,
    FOVRadius: 500,
    maxAmount: 5,
    name: "luminousSpiritTreant",
    side: "glowGarden",
    appearance: "mob/luminousSpiritTreant.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: false,
    setMinHealth: 20,
    setMaxHealth: 70,
    defense: 1,
    damage: 3,
    type: "summoner",
    ability: "aimedCasting",
    learnedSpells: summonSpirit,
    castAmount: 3,
    castDelay: 180,
    experienceDrop: 20,
    lootDrop: [glowEssence, luminousSpiritPage, manaOrb],
    intelligence: 0,
    respawnTime: 32000
};
const wanderingFog = {
    setMinX: 0,
    setMaxX: 2000,
    setMinY: 2000,
    setMaxY: 8000,
    radiusAdjust: 30,
    movementSpeed: 1,
    turnSpeed: null,
    FOVRadius: 250,
    maxAmount: 5,
    name: "wanderingFog",
    side: "gloomForest",
    appearance: "mob/wanderingFog.png",
    ignoreSpellCollision: true,
    ignoreMobCollision: true,
    setMinHealth: 100,
    setMaxHealth: 150,
    defense: 7.5,
    damage: 0,
    type: "passive",
    ability: "shrinksOnDamage",
    learnedSpells: null,
    castAmount: null,
    castDelay: null,
    experienceDrop: 15,
    lootDrop: [gloomEssence, manaOrb],
    intelligence: 1,
    respawnTime: 8000
};