// spell books
const spikeBook = {
	appearance: "spellBook/spike_spellBook.png",
	name: "spikeBook",
	cooldown: 30,
	text: "spike",
	spell: castSpike = {
		radius: 12,
		FOVRadius: 0,
		name: "castSpike",
		art: "projecting",
		shape: "circle",
		appearance: "spell/spike.svg",
		castAmount: 1,
		maxAmount: 0,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 5,
		defense: 0,
		damage: 3,
		speed: 10,
		ability: "shoot1",
		manaCost: 0.1,
		summonCost: 0,
		respawnTime: 500
	},
	spellCore: spikeCore = {
		radius: 12,
		FOVRadius: 0,
		name: "spikeCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/spike_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const luminousEnergyBook = {
	appearance: "spellBook/luminousEnergy_spellBook.png",
	name: "luminousEnergyBook",
	cooldown: 60,
	text: "lumenergy",
	spell: castLuminousEnergy = {
		radius: 5,
		FOVRadius: 0,
		name: "castLuminousEnergy",
		art: "projecting",
		shape: "circle",
		appearance: "mob/luminousRock.svg",
		castAmount: 5,
		maxAmount: 5,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 5,
		defense: 0,
		damage: 1,
		speed: 15,
		ability: "shoot2",
		manaCost: 1.25,
		summonCost: 0,
		respawnTime: 1000
	},
	spellCore: luminousEnergyCore = {
		radius: 12,
		FOVRadius: 0,
		name: "luminousEnergyCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/luminousEnergy_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const glowShardBook = {
	appearance: "spellBook/glowShard_spellBook.png",
	name: "glowShardBook",
	cooldown: 60,
	text: "glow Shard",
	spell: castGlowShard = {
		radius: 5,
		FOVRadius: 0,
		name: "castGlowShard",
		art: "projecting",
		shape: "circle",
		appearance: "spell/glowShard.png",
		castAmount: 3,
		maxAmount: 3,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 10,
		defense: 3,
		damage: 3,
		speed: 20,
		ability: "shoot2",
		manaCost: 5,
		summonCost: 0,
		respawnTime: 1000
	},
	spellCore: glowShardCore = {
		radius: 12,
		FOVRadius: 0,
		name: "glowShardCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/glowShard_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const luminousShieldBook = {
	appearance: "spellBook/luminousShield_spellBook.png",
	name: "luminousShieldBook",
	cooldown: 90,
	text: "shield",
	spell: summonLuminousShield = {
		radius: 120,
		FOVRadius: 0,
		name: "summonLuminousShield",
		art: "summoning",
		shape: "circle",
		appearance: "mob/luminousRock.svg",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 240,
		defense: 2.5,
		damage: 0.1,
		speed: 5,
		ability: "summon1",
		manaCost: 1,
		summonCost: 5,
		respawnTime: 1000
	},
	spellCore: luminousShieldCore = {
		radius: 12,
		FOVRadius: 0,
		name: "luminousShieldCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/luminousShield_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const luminousSpiritBook = {
	appearance: "spellBook/luminousSpirit_spellBook.png",
	name: "luminousSpiritBook",
	cooldown: 120,
	text: "spirit",
	spell: summonSpirit = {
		radius: 20,
		FOVRadius: 0,
		name: "summonSpirit",
		art: "summoning",
		shape: "circle",
		appearance: "mob/luminousSpirit.svg",
		castAmount: 5,
		maxAmount: 5,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 20,
		defense: 0,
		damage: 3.5,
		speed: 5,
		ability: "summon1",
		manaCost: 2.5,
		summonCost: 2,
		respawnTime: 1000
	},
	spellCore: luminousSpiritCore = {
		radius: 12,
		FOVRadius: 0,
		name: "luminousSpiritCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/luminousSpirit_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const specterBook = {
	appearance: "spellBook/specter_spellBook.png",
	name: "specterBook",
	cooldown: 120,
	text: "specter",
	spell: summonSpecter = {
		radius: 25,
		FOVRadius: 0,
		name: "summonSpecter",
		art: "summoning",
		shape: "circle",
		appearance: "mob/specter.svg",
		castAmount: 4,
		maxAmount: 4,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 35,
		defense: 0,
		damage: 4.5,
		speed: 7,
		ability: "summon1",
		manaCost: 4,
		summonCost: 2.5,
		respawnTime: 1500
	},
	spellCore: specterCore = {
		radius: 12,
		FOVRadius: 0,
		name: "specterCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/specter_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const specterHandBook = {
	appearance: "spellBook/specterHand_spellBook.png",
	name: "specterHandBook",
	cooldown: 90,
	text: "hand",
	spell: castSpecterHand = {
		radius: 5,
		FOVRadius: 0,
		name: "castSpecterHand",
		art: "projecting",
		shape: "circle",
		appearance: "spell/specterHand.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 30,
		defense: 1.5,
		damage: 4.5,
		speed: 7.5,
		ability: "shoot3",
		manaCost: 3.5,
		summonCost: 0,
		respawnTime: 1500
	},
	spellCore: specterHandCore = {
		radius: 12,
		FOVRadius: 0,
		name: "specterHandCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/specterHand_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const teleportBook = {
	appearance: "spellBook/teleportation_spellBook.png",
	name: "teleportBook",
	cooldown: 90,
	text: "teleport",
	spell: teleport = {
		radius: 50,
		FOVRadius: 0,
		name: "teleport",
		art: "evading",
		shape: "circle",
		appearance: "spell/teleportation.png",
		castAmount: 1,
		maxAmount: 0,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 15,
		defense: 0,
		damage: 0,
		speed: 30,
		ability: "teleport",
		manaCost: 2,
		summonCost: 0,
		respawnTime: 500
	},
	spellCore: teleportCore = {
		radius: 12,
		FOVRadius: 0,
		name: "teleportCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/teleportation_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const smashBook = {
	appearance: "spellBook/smash_spellBook.png",
	name: "smashBook",
	cooldown: 30,
	text: "smash",
	spell: smash = {
		radius: 30,
		FOVRadius: 0,
		name: "smash",
		art: "AoE",
		shape: "circle",
		appearance: "spell/smash.png",
		castAmount: 15,
		maxAmount: 0,
		ignoreSpellCollision: true,
		ignoreMobCollision: false,
		index: 1,
		health: 1,
		defense: 100,
		damage: 2.5,
		speed: 0,
		ability: "AoE1",
		manaCost: 3,
		summonCost: 0,
		respawnTime: 500
	},
	spellCore: smashCore = {
		radius: 12,
		FOVRadius: 0,
		name: "smashCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/smash_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const beamBook = {
	appearance: "spellBook/beam_spellBook.png",
	name: "beamBook",
	cooldown: 120,
	text: "beam",
	spell: castBeam = {
		radius: 0,
		FOVRadius: 0,
		name: "castBeam",
		art: "beams",
		shape: "line",
		appearance: "spell/beam.png",
		castAmount: 1,
		maxAmount: 0,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 10000,
		defense: 0,
		damage: 0.5,
		speed: 10,
		ability: "beam1",
		manaCost: 1,
		summonCost: 0,
		respawnTime: 500
	},
	spellCore: beamCore = {
		radius: 12,
		FOVRadius: 0,
		name: "beamCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/beam_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const lightningBoltBook = {
	appearance: "spellBook/lightningBolt_spellBook.png",
	name: "lightningBoltBook",
	cooldown: 90,
	text: "lightning",
	spell: castLightningBolt = {
		radius: 0,
		FOVRadius: 0,
		name: "castLightningBolt",
		art: "beams",
		shape: "line",
		appearance: "spell/lightningBolt.png",
		castAmount: 5,
		maxAmount: 0,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 1,
		defense: 0,
		damage: 10,
		speed: 10,
		ability: "beam2",
		manaCost: 2,
		summonCost: 0,
		respawnTime: 500
	},
	spellCore: lightningBoltCore = {
		radius: 12,
		FOVRadius: 0,
		name: "lightningBoltCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/lightningBolt_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}
const energyBallBook = {
	appearance: "spellBook/energyBall_spellBook.png",
	name: "energyBallBook",
	cooldown: 90,
	text: "energy ball",
	spell: castEnergyBall = {
		radius: 50,
		FOVRadius: 0,
		name: "castEnergyBall",
		art: "projectile",
		shape: "circle",
		appearance: "spell/energyBall.png",
		castAmount: 1,
		maxAmount: 0,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 2500,
		defense: 0,
		damage: 3,
		speed: 10,
		ability: "shoot1",
		manaCost: 1,
		summonCost: 0,
		respawnTime: 500
	},
	spellCore: energyBallCore = {
		radius: 12,
		FOVRadius: 0,
		name: "energyBallCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/energyBall_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	},
}
const treeBook = {
	appearance: "spellBook/summonTree_spellBook.png",
	name: "treeBook",
	cooldown: 120,
	text: "tree",
	spell: summonTree = {
		radius: 50,
		FOVRadius: 0,
		name: "summonTree",
		art: "summoning",
		shape: "circle",
		appearance: "mob/gloomForestTree.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: false,
		ignoreMobCollision: false,
		index: 1,
		health: 50,
		defense: 3,
		damage: 0.5,
		speed: 0,
		ability: "summon2",
		manaCost: 3,
		summonCost: 2,
		respawnTime: 1500
	},
	spellCore: treeCore = {
		radius: 12,
		FOVRadius: 0,
		name: "treeCore",
		art: "books",
		shape: "circle",
		appearance: "spellBook/summonTree_spellBook.png",
		castAmount: 1,
		maxAmount: 1,
		ignoreSpellCollision: true,
		ignoreMobCollision: true,
		index: 1,
		health: 100,
		defense: 100,
		damage: 0,
		speed: 12,
		ability: null,
		manaCost: 1,
		summonCost: 0,
		respawnTime: null
	}
}